apiVersion: v1
kind: Secret
metadata:
  name: auth-credential
  labels:
    app: postgres
data:
  JWT_KEY: c3VwZXItc2VjcmVjdC1qd3QtdmFsdWUtZm9yLW15LWF1dGg=
  DB_URL: cG9zdGdyZXM6Ly9mdmxpa3B2dTpKSmY1ODdSZjRRNHpMeEdiX012aDlYaU5zY1dVV2dpV0Bqb2huLmRiLmVsZXBoYW50c3FsLmNvbS9mdmxpa3B2dQ==
  EMAIL_USER: c291cmF2bWFqdW1kYXIuZGV2ZWxvcGVyQGdtYWlsLmNvbQ==
  EMAIL_APP_PASSWORD: a21rdyBkZXNmIGNheHogd3RhYg==
