apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfe-host-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfe-host
  template:
    metadata:
      labels:
        app: mfe-host
    spec:
      containers:
        - name: mfe-host
          image: souravdeveloper/ecom-mfe-host
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mfe-host-srv
spec:
  selector:
    app: mfe-host
  type: ClusterIP
  ports:
    - name: mfe-host
      targetPort: 3000
      port: 3000
      protocol: TCP

