apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfe-shared-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfe-shared
  template:
    metadata:
      labels:
        app: mfe-shared
    spec:
      containers:
        - name: mfe-shared
          image: souravdeveloper/ecom-mfe-shared
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mfe-shared-srv
spec:
  selector:
    app: mfe-shared
  type: ClusterIP
  ports:
    - name: mfe-shared
      targetPort: 3000
      port: 3000
      protocol: TCP

