apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfe-user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfe-user
  template:
    metadata:
      labels:
        app: mfe-user
    spec:
      containers:
        - name: mfe-user
          image: souravdeveloper/ecom-mfe-user
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mfe-user-srv
spec:
  selector:
    app: mfe-user
  type: ClusterIP
  ports:
    - name: mfe-user
      targetPort: 3000
      port: 3000
      protocol: TCP

